services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql:/tmp/init.sql
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - db_network
    restart: "no"

  pgadmin:
    image: dpage/pgadmin4:6.19
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: $PG_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PG_ADMIN_PASSWORD
    ports:
      - "8888:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_network
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sarkiisov/platesmania-backend:latest
    container_name: backend_app
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - db_network
    restart: "no"

volumes:
  postgres:
  pgadmin:

networks:
  db_network:
    driver: bridge
